print("+=====================================================+")
print("|     Selamat Datang di Kalkulator Metode Simplex     |")
print("+-----------------------------------------------------+")
print("|  Author : arifrizqy                                 |")
print("|  Github repo :                                      |")
print("|        https://github.com/arifrizqy/simplex-method  |")
print("+=====================================================+")
print()
print("Tata cara penggunaan :")
print("1. ")